name: HackMatrix Bot Issues cmp
run-name: ${{ github.actor }}  cmp
on: [push]
jobs:
  RunHackMatrixBot:
    runs-on: ubuntu-latest
    steps:
      - uses: collinalexbell/AnonTheHackMatrixBot@v3
        with: 
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          repo-owner: "collinalexbell"
          repo-name: "HackMatrix"
        
